### ISSUE TITLE
Game can not completly paused in "Arcade" mode.

### ISSUE THREAD

**Issue by Herb1** [Acagamics/virusx#14]
The game can not completly paused in Arcade mode. Cells disappear immediately after the game continues.

**Comment by Wumpf** [comment]
This does not only affect the Arcade mode. Practically all timed events are a bit broken since most of them use System.Diagnostics.Stopwatch to keep track of time - they keep ticking while being in Pause. Instead, we need something like a GameStopwatch which only runs while the game is unpaused.

**Comment by Wumpf** [comment]
Not solved as proposed but this should do the trick. Animation timers etc. are still Stopwatches but those are not that important.
