### ISSUE TITLE
Finalize appxmanifest & related icons

### ISSUE THREAD

**Issue by Wumpf** [Acagamics/virusx#7]
Need to fill out description and icons etc. to be ready to submit the app to the windows store.
While we're on it we should investigate all the other requirements in detail.

**Comment by Wendesil** [comment]
Can you post the full list of failed requirements?

**Comment by Wumpf** [comment]
See #10 for concrete issues other than icons for what I know so far. I started setting up the store app, but haven't gone through everything, so there are some open questions. E.g. it looks like there is no way to change the displayed author for a game without creating a new account. I planned to put a "hidden store app" yesterday so send it around, but then I got the issues mentioned in #10. I hope I'll have something before the end of this week, but can't promise anything. Stay tuned.

**Comment by Wumpf** [comment]
Repo should work out of the box by now though. So if you want to give it a try don't hesitate!
